---
language: rust
dist: trusty
# TODO: coverage
# TODO: smoketest fuzzers

rust:
  - stable

script:
  - cargo build --all --verbose
  - cargo build --all --features=alloc --no-default-features
  - cargo build --all --no-default-features

  - cargo test --all --verbose
  - cargo test --all --no-default-features
  # use `--tests` to skip doctests for the `alloc` feature, since they
  # fail because of https://github.com/rust-lang/rust/issues/54010
  - cargo test --tests --features=alloc --no-default-features

