[package]
name = "base16"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]
keywords = ["hex", "hexadecimal", "base16", "encode", "decode"]
description = "base16 (hex) encoding and decoding"
categories = ["encoding"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]

[dev-dependencies]
rand = "0.4"
