version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - Run tests

jobs:
  Run tests:
    docker:
      - image: circleci/rust:1.36.0

    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version

      - run:
          name: Test (all features)
          command: cargo test --all --verbose
      - run:
          name: Test (only alloc)
          # use `--tests` to skip doctests for the `alloc` feature, since they
          # fail because of https://github.com/rust-lang/rust/issues/54010
          command: cargo test --tests --features=alloc --no-default-features
      - run:
          name: Test (no std or alloc)
          command: cargo test --all --no-default-features
